// Electron main process for the CivicScribe Recorder.
//
// Two jobs:
//  1. Answer getDisplayMedia() with `audio: 'loopback'`, which is what lets the
//     renderer capture SYSTEM audio on Windows (WASAPI) with no native code.
//     This is the whole reason the public path needs no bot in the meeting.
//  2. Own the local WAV safety copy. The renderer streams PCM over IPC and we
//     append it to disk, so a dropped network connection never loses a meeting.

import { app, BrowserWindow, session, desktopCapturer, ipcMain } from "electron";
import path from "node:path";
import { mkdir, readFile } from "node:fs/promises";
import { WavWriter } from "./wav-writer";

let writer: WavWriter | null = null;
let currentPath = "";
let mainWindow: BrowserWindow | null = null;

function recordingsDir(): string {
  return path.join(app.getPath("documents"), "CivicScribe Recordings");
}

app.whenReady().then(async () => {
  session.defaultSession.setDisplayMediaRequestHandler((_request, callback) => {
    // We only want the audio; a video source must still be named for the
    // request to resolve, and the renderer stops the video track immediately.
    desktopCapturer
      .getSources({ types: ["screen"] })
      .then((sources) => callback({ video: sources[0], audio: "loopback" }))
      .catch(() => callback({}));
  });

  const win = new BrowserWindow({
    width: 820,
    height: 680,
    title: "CivicScribe Recorder",
    // Generated by scripts/make-icon.mjs. .ico carries every size Windows wants
    // for the taskbar and title bar.
    icon: path.join(__dirname, "..", "..", "build", "icon.ico"),
    webPreferences: { preload: path.join(__dirname, "preload.cjs") },
  });

  // Screen-share invisibility. On Windows this sets WDA_EXCLUDEFROMCAPTURE: the
  // window stays visible to the operator but is omitted from screen captures and
  // screen shares, so the recorder UI never leaks into a shared screen.
  //
  // This hides the WINDOW, not the fact of recording. Local (no-bot) capture is
  // restricted to public meetings, where recording is lawful under the MA Open
  // Meeting Law; private meetings keep the self-announcing bot.
  win.setContentProtection(true);
  mainWindow = win;

  // RECORDER_MOCK=1 runs the whole flow with a fake transcriber and no backend,
  // matching the app's keyless MOCK_MODE demo path.
  const mock = process.env.RECORDER_MOCK === "1";
  await win.loadFile(
    path.join(__dirname, "..", "src", "renderer", "index.html"),
    mock ? { query: { mock: "1" } } : undefined
  );
});

app.on("window-all-closed", () => app.quit());

ipcMain.handle(
  "recording-start",
  async (_event, sessionId: string, sampleRate: number): Promise<string> => {
    const dir = recordingsDir();
    await mkdir(dir, { recursive: true });
    // sessionId is a server-issued uuid, but keep the filename defensive.
    const safe = sessionId.replace(/[^a-zA-Z0-9._-]/g, "_");
    currentPath = path.join(dir, `${safe}.wav`);
    writer = await WavWriter.create(currentPath, sampleRate);
    return currentPath;
  }
);

ipcMain.handle("set-invisible", (_event, invisible: boolean): boolean => {
  mainWindow?.setContentProtection(invisible);
  return invisible;
});

ipcMain.on("audio-chunk", (_event, buf: ArrayBuffer) => {
  // Fire-and-forget by design: WavWriter serializes writes internally, and a
  // dropped chunk must never block the audio pipeline.
  writer?.append(new Int16Array(buf));
});

ipcMain.handle("recording-finalize", async () => {
  if (!writer) throw new Error("no recording in progress");
  const result = await writer.finalize();
  writer = null;
  return { path: currentPath, ...result };
});

ipcMain.handle("read-recording-bytes", async (): Promise<ArrayBuffer> => {
  const buf = await readFile(currentPath);
  return buf.buffer.slice(
    buf.byteOffset,
    buf.byteOffset + buf.byteLength
  ) as ArrayBuffer;
});
