// Builds a small HTML page showing the generated icon at every packed size,
// on light and dark backgrounds. Preview only; not part of the app.

import { readFileSync, writeFileSync } from "node:fs";

const b64 = readFileSync("build/icon.png").toString("base64");
const sizes = [16, 24, 32, 48, 64, 128, 256];

const tiles = sizes
  .map(
    (s) =>
      `<figure><img src="data:image/png;base64,${b64}" width="${s}" height="${s}" alt="${s}px"><figcaption>${s}px</figcaption></figure>`
  )
  .join("");

const html = `<meta charset="utf-8">
<title>CivicScribe Recorder icon</title>
<style>
  body { font: 15px system-ui, sans-serif; background: #f6f7f9; color: #14181f; margin: 0; padding: 32px; }
  h1 { font-size: 18px; margin: 0 0 4px; }
  p.sub { color: #5b6472; margin: 0 0 26px; font-size: 13px; }
  .strip { display: flex; align-items: flex-end; gap: 26px; flex-wrap: wrap;
           background: #fff; border: 1px solid #e2e6ec; border-radius: 12px; padding: 26px; }
  .strip.dark { margin-top: 22px; background: #12151a; border-color: #2b323d; }
  .strip.dark figcaption { color: #98a2b3; }
  figure { margin: 0; text-align: center; }
  figcaption { font-size: 11px; color: #5b6472; margin-top: 8px; }
  img { display: block; }
</style>
<h1>CivicScribe Recorder - app icon</h1>
<p class="sub">Generated by scripts/make-icon.mjs with no image dependencies. Shown at the sizes packed into icon.ico.</p>
<div class="strip">${tiles}</div>
<div class="strip dark">${tiles}</div>`;

writeFileSync("build/icon-preview.html", html);
console.log("wrote build/icon-preview.html");
